# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing
exec-once = ~/.config/hypr/custom/scripts/auto_idle_inhibit.sh
exec-once = ~/.config/hypr/custom/scripts/screen_off_on_lock.sh
